<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserDemoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        // User::create([
        //     'name' => 'Eko Ari',
        //     'email' => 'eko@demo.com',
        //     'password' => Hash::make('12345678')
        // ]);

        DB::table('users')->insert([

            [
                'name' => 'Administrator',
                'email' => 'admin@app.com',
                'password' => bcrypt('password'),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            ['name' => 'dr. RAKKA DWIMAREFFY HAROLDIWULAN', 'email' => '20199112082-RAKA@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'drg. HENDRA PUTRA SETYAWAN', 'email' => 'drg.setyawan@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'dr. AGENG BAGUS SADEWO', 'email' => '20239709061-AGENG@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'dr. OLIVIA DEVINA PERMATASARI', 'email' => '20239707075-OLIVIA@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'dr. NABILAH NOOR RABBANI', 'email' => 'nabilnr22@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MUKHAMAD HASAN, S. Kep. Ners', 'email' => 'mukhamadhasan374@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MUHAMMAD FAIZIN, S. Kep. Ners', 'email' => '20169204001-FAIZIN@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ARDHANUDHIN, S.Kep.Ners', 'email' => 'ardhanudhin13@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ZAHRAUL MUFIDA, S.Tr.Kep', 'email' => 'zahraulmufidah1@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ELINDA MIFTAHUR ROHMAH S.Tr.Kep., Ns', 'email' => 'elindamifta@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FADHIL RIZQI RAHMATULLAH S.Tr.Kep., Ns', 'email' => 'fadhilr846@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'AKHMAD KHOLIL, S. Kep. Ners', 'email' => 'kholilakhmad75@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MEIKE SYLVIANA,S.Kep.Ners', 'email' => 'meikesylviana11@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'PUTRI DINIARI WIRA OKTAVIA, S.Kep.Ners', 'email' => 'putridini020@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ASYIFA AMALIA RIKZA AMANSI,S.Kep.Ners', 'email' => 'asyifaamaliarikzaamansi@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'YAYANG RIDHO SETIYOSO, S.Kep.Ners', 'email' => 'yrsetiyoso@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ICHWANUL HAKIM, S.Kep.Ners', 'email' => 'ichwanh@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'PUNGKI DINARTIKA, Amd.Kep ', 'email' => 'pungkidinartika01@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FRISTY NUR AMALIA FLORANTI,Amd.Kep', 'email' => 'fristyamalia08@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'LINDA AMELIA ARIFIN,Amd.Kep', 'email' => 'lindaamelia550@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RELA YOULANDA P., Amd.Kep', 'email' => 'relayoula87@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SITI AFIFAH, Amd. Kep', 'email' => 'ifaafifah520@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'HERI KUSNADI, Amd.Kep', 'email' => 'heriku123@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FANDIK DWI NUR C, S.Kep.Ners', 'email' => 'fandikdwinurcahyono@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FAUZIZAH RAHMAH N, S.Kep.Ners', 'email' => 'ramma.fau@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ZAIDA , S.Kep.Ners', 'email' => 'zaida_elok@yahoo.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'WINDA SUCI WULANDARI, S.Kep. Ners', 'email' => 'windasuciwulandari@gmail.com ', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DEVI PUTRI WIJAYANTI,S.Kep.Ners', 'email' => 'devi.putri30@gmail.com ', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RATIH PRAHAPSARI SOMADHINI, S.Kep.Ners', 'email' => 'sratihprahapsari27@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'YUSI IDAH SAFITRI, S.Tr.Kep', 'email' => 'yusiidahsafitri@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'TAUFIK HIDAYAT, Amd. Kep ', 'email' => 'taufikanggi08@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DONY EKO HERMAWAN, Amd.Kep', 'email' => 'donie2380@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'YULIA ANDRIANI, Amd.Kep', 'email' => 'yuliaa912@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ELA ELISA, Amd.Kep', 'email' => 'elaelisa3507@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SHELLA NOVELIANI, Amd.Kep', 'email' => 'shellanovel21@gmail.com ', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ERITA ARDINI, Amd. Kep', 'email' => 'eritaardini20@gmail.com ', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'NISYA DIYAH ANGGRAENI, Amd.Kep', 'email' => 'nisyadiyah1@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SITI ALMIRA FARIHAN,Amd.Kep', 'email' => 's.almirafar@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'AMANDA AURA MAHARANI,Amd.Kep', 'email' => 'amandaaura62@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'YULVIA LAILA NUR YUHA, Amd.Kep', 'email' => 'yulvialaila@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RIZKI SILFIANA, S. Kep Ners', 'email' => 'rizkisilfiana21061994@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'WIDYA MUHARYANTO, S.Kep', 'email' => 'widyamuharyanto81@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'YUNITA DWI FARADILA, S.Kep.Ners', 'email' => 'yunitadfaradila@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RIZKI PUTRI PAMUNGKASSARI, S.Tr.Kep', 'email' => 'ichyputri251@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SYAFRIANTY FERDHITA ALFIRIZA', 'email' => 'alfirizaferdhita@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'JIMIA KRISTIN, S.Tr.Kep', 'email' => 'kristinjimia@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FENDI SETYO UTOMO, Amd Kep', 'email' => 'fendisetyoutomo@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MARETHA RAMADHANI FIRRIZQI, Amd.Kep', 'email' => 'maretha960@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'INDRI ISMAWAN, Amd.Kep', 'email' => 'indriismawan@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'NILA SARI, Amd.Kep', 'email' => 'nilasarithok@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ERIK ROMADHON,  Amd.Kep', 'email' => 'romadhonerik@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RIZKA MUFARIDA, Amd.Kep', 'email' => 'rizkamufarida@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DENOK DWI AJENG WINANTU R. ', 'email' => 'denokdwiajeng@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ASFARY ZAHIDAH PANGESTUTI', 'email' => '181008.asfaryzahidah@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ROSA ROSITA, Amd. Kep', 'email' => 'rosarosita688@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DIAH FATMAWATI, S.Kep. Ners', 'email' => 'asyadiaatma@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ANGGA GIGIH YUDISTIRA, S. Kep. Ners', 'email' => 'anggagigihy@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'AGUNG WICAKSONO, S.Kep.Ners', 'email' => 'agoengwicakzone95@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DIAH NIATI, S.Kep.Ners', 'email' => 'diahniati2@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FLORENCIA YUNAIKE SINDIAWATI,S.Kep.Ners', 'email' => 'yunaikeflorencia@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DEDY SETYO P, Amd Kep', 'email' => 'dedysetyo456@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'QOTRUNNADA SALSABILA, Amd.Kep', 'email' => 'nadhasb6@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MEYDINA ARSYA PRASTIKA,Amd.Kep', 'email' => 'meydina.meme18@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ARI DWI KRISTANTO, Amd.Kep', 'email' => 'aridwikristanto01@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MUHAMMAD HILAL NAZMI, Amd.Kep', 'email' => 'hilalabrt@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FIKRI AJI PAMADI, Amd.Kep', 'email' => 'ajifikri348@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'WULAN VITASARI, Amd. Kep', 'email' => 'wulanvitasari94@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RINAWATI Amd. Kep', 'email' => 'ririnrina93@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MARISKA AYU. P, Amd. Kep', 'email' => 'mariskaayu69@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ICUT NOFIKA SARI, Amd.Kep', 'email' => 'nofikasari721@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DEA NOVITA WULANDARI, Amd.Kep', 'email' => 'deanovita77.dn@gmail.com ', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'PUTRI ARIAN DEWI, Amd.Keb', 'email' => 'putriariyan10@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ULLY RISNA INDRAYANI, Amd. Kep', 'email' => 'ullyrisna2227@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ANGGI SRIMAWARNI PUTRI,Amd.Kep', 'email' => 'anggisrimawarni@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FADHILAH RAHAYU, Amd.Kep', 'email' => 'fadhilahrahayu77@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FERIKA IRMA N, Amd. Kep', 'email' => 'ferikairma@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'PIPIT KURNIATUL LAILA, S.Kep..Ns', 'email' => 'pipittriana17@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FRANSISKA PRAMEISELA, S.Kep.Ners', 'email' => 'fprameisela@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FIFI NURINDAH SARI, Amd.Kep', 'email' => 'fifinurindahsari18@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SRIMAWATI WAHYUNINGSIH,Amd.Fis', 'email' => 'wsrima35@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RENANDA NUR AFIKA, Amd.Kep', 'email' => '20220011034-RENANDA@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DEWI PUJI W., Amd.Kes', 'email' => 'dewipujiwurnani@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FARIDA HANUNG, S. Tr. Keb', 'email' => 'farhan250494@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'WAHNINGYUN, Amd.Keb', 'email' => 'wahningyun@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SRI MUMPUNI, Amd. Keb', 'email' => 'allysaconchita2@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'AMALIA ROSDIANA E, Amd Keb', 'email' => 'arosdiana27@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MITA KURNIASARI, Amd Keb', 'email' => 'edlomi88@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FENI PUSPITA I,Amd. Keb', 'email' => '20128907002-FENIPUS@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ANGGI PUJA, Amd. Keb', 'email' => 'Aleena170519@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ALIF FATMAWATI, Amd. Keb', 'email' => 'alif.rasyid24@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SELLA CINTHA RAMADHANI, Amd. Keb', 'email' => 'sella.cintha24@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'NUR DIAH, Amd.Keb', 'email' => '20179503023-NURDIAH@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SRI WAHYUNINGSIH, Amd. Keb', 'email' => 'ayuwahyu253@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ASTI SETYA S., S.Kep. Ners', 'email' => 'asti.sawitri@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DIAN ANGGRAINI, S.Kep. Ners', 'email' => 'dianangrainii989@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'LUTFIA KAUTSAR A., Amd.Kes', 'email' => 'lutfiaardian@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'IKA  WIJAYANTI', 'email' => 'ikatralala46@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'BELLA PRASTIKA', 'email' => 'bellaprastika1998@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RINI ERNI SISWATI, Amd. RMIK', 'email' => 'riny13.er@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'NIDA DIFITRI, Amd. RMIK', 'email' => 'nidadifitri@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'INDIRA GIRI M, Amd. RMIK', 'email' => 'indiragirimaharani@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DWI NOR AISYAH PRATIWI, S.T', 'email' => 'dwipratiwi757@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'WINIE AYU DEA, Amd.RMIK', 'email' => 'Winiedea96@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MAHATMA MARWA GANANTAMA', 'email' => 'elfmahatma@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DEA MAURITA FACHRIYAH,Amd.RMIK', 'email' => 'mauritadhea@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'BEKTASIO ASARETHA SARDJANA, Amd.RMIK', 'email' => 'bektasioasaretha@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ISMAUL NIZA AISHA VERA, Amd. RMIK', 'email' => 'ismaulnisa@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'EKO ARI IRAWAN, S.Kom', 'email' => 'ekoariirawan11@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DANDUNG SATRIO WULANG JIWO', 'email' => 'satriodandung00@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DINAR BUGI MAWARNI, S. Farm. Apt', 'email' => 'dynar.dbam2007@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ELINA ANGGRAINI MULYANINGSIH, S.Farm.Apt', 'email' => 'apt.elina25@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'CHRISMA DESI ANDRIATI, S.Farm.Apt', 'email' => 'chrismaandriati15@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'BAGUS RENDI KURNIANTO, Amd. Farm', 'email' => 'bagoeskwr@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'TITIN CATUR , Amd. Farm', 'email' => 'titincaturwulandari@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'NIA MARTINI', 'email' => 'nia0509@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'HERLINA EVI NUR CAHYA', 'email' => 'herlinanurc17@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'PUTRI ZAHROTUL ISNAINIYAH', 'email' => 'putrizahro073@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'YOHANES ADVENTIONE PRIANGGORO,Amd.FARM', 'email' => 'yohanesap99@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'YUDIANA SANDI WATININGSIH,Amd.FARM', 'email' => 'yudianasandi2@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SALSABILLA ZAHRA WAHIDAH,Amd.Kes', 'email' => 'salsabillazahraw@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RINDA SEPTIA ELTIANA', 'email' => 'rindaseptia140996@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'IKE PRATAMA DINA SABILA', 'email' => 'ikepratama2@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'NURUL HIKMAH, Amd.Kes', 'email' => 'nurulhkmah14@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'PUTRI KHOIRUN NISA, Amd.Kes', 'email' => 'putrikhoirunnisa.231098@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ALFADHIKA PRINGGO SANGGA SUKMA', 'email' => 'alfadhikathetomen@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SADGASSUSI HERA SAMUDRA ', 'email' => 'sadgassus83@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'NAILA IFTITAH MAHDIYANA, Amd. Rad', 'email' => 'iftitahnaila22@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'YULIASIH SATYO RINI, Amd. Rad', 'email' => 'yulisatiorini26@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DELA NOVITA, Amd.Rad', 'email' => 'delayukino1@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'TIO PRAMBUDI, Amd.Rad', 'email' => 'prambuditio@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'YUDHA PANGESTU WIDODO, Amd.Rad', 'email' => 'yudhapangestu840@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MITA EKA BUDIARTI, S. Gz', 'email' => 'mitaekabudiarti@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RISKA INDRAWATI, S.Gz', 'email' => 'riskaindrawati63@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RIZKY NOVITASARI', 'email' => 'riskynovitasari92@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DEVI REVIANA ', 'email' => 'Devireviana256@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ROSA LAILATUS SA DIYAH ', 'email' => 'rosalailatus6@gmail.com ', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RIKA PUSPITASARI', 'email' => 'rikapuspitasari@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'INDRASARI AYUNDA PUTRI', 'email' => 'Indrasariayundaputri@gmail.com ', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ARDIANA SUYATNI AROHMA NIRUM', 'email' => 'arumadriana@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MUHAMMAD SYAIFUDIN ZUHRI', 'email' => 'Muhh009@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RIO ARYA SAPUTRA', 'email' => 'rio17ompol@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MARATUS SHOLIHAH APRILIA KOSASIH, S.Ak', 'email' => 'maratusaprilia97@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'LAVITTA YULIA, S.Pd', 'email' => 'lavittayulia17@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ARIFATUL IZZA, S. H', 'email' => 'arifatulizzah7@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FENNI AGISTA PUSPITA', 'email' => 'fenni.agista@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'LIA NURINA', 'email' => 'Lianurina43@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'NISA YULIANTI TENDEAN, S.Si', 'email' => 'nisayulianti08@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'INTAN DEWI SA ADAH, S.Ak', 'email' => 'intand420@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'LILITH CHINTHANIA, Amd. Ak', 'email' => 'lilithchinthania@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SUCI WULANDARI FITRIANI ', 'email' => 'icusoktafitria@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SUTARMI', 'email' => 'aamy15470@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RIZKY ISWAHYUDI PRATAMA', 'email' => 'rizkyiswahyudi26@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'AHMAD ARIS S.', 'email' => 'salsabilaris22@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'HIKMAH SHOFIYAH', 'email' => 'hikmahshofiyah29@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'LIDIYA DWI PUTRI SARI, S.Sos', 'email' => 'lidiyadwiputrisari@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'AMIN', 'email' => '20116807008-AMIN@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'HELMY PRAKOSO', 'email' => 'bademiganteng@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'HERIANTO', 'email' => 'herianto heri@9mailvom', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ANDIK SUMARTONO', 'email' => '20137301005-ANDIK@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'YUSUP WAHYU SETYAWAN', 'email' => 'wahyuyusuff2016@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DEDI FEBRI PRATAMA ', 'email' => '20199102054DEDI@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'QHOIRUL SETIAWAN ', 'email' => '20199503051-QHOIRUL@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FENDIK PRAYOGO ', 'email' => 'fendikprayogo6@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SULISWANTO', 'email' => 'azmifalishanadhira081@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ANDHIKA DWI PRASETYA PUTRA', 'email' => 'andhikadwi1509@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ROMDHONI', 'email' => 'markaban181@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SHINTA BELLA AGUSTIN', 'email' => 'shintabella1381@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'EKO HERU ', 'email' => 'aldoopranata1@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SUGIONO', 'email' => 'sugi04476@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'LUKMAN FAUZI ', 'email' => 'lukman.derryl87@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SUPARDI', 'email' => 'gonzalessupardi@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'HADI HERMANTO', 'email' => 'hadihermanto057@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MOCHAMMAD ALFAN P', 'email' => '20179803010-ALFAN@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'CHRISBIANTO GUNAWAN', 'email' => 'krisbiantoo225@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'YOGANATA HERVIANTO', 'email' => '20179201020-YOGANATA@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MUHAMMAD SOFYAN ZAHRI SALDI', 'email' => 'sofyanzahri@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DIKA ADITYA PUTRA PRATAMA ', 'email' => 'dikaadityaputrapratama30@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'HANIF FAHRUROH', 'email' => '20209106017-HANIF@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'OCKY PRISMA EFENDY', 'email' => 'aliprisma8@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'AHMAD HAYIZ HAYDAR', 'email' => '20219410001-AHMADHAYIZ@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ABDUL QODIR', 'email' => 'abdulqodir089687@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'KURNIA YUNINGRUM ROHMASARY, Amd.Kep ', 'email' => 'kurniarohmasary@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MIFTAKHUL ILMI, Amd.Kep', 'email' => 'miftakhulilmi42@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ANASTA PRAVANGHESTI KUSUMA ANGGI, Amd.Kep', 'email' => 'anastaanggi@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'AFIF RAHMAN MAULANA, Amd.Kep', 'email' => 'apiprahman120@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'MUTHIA RIZQY FADHILAH, S.FARM', 'email' => 'muthiaf16@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ARYANANDO', 'email' => 'aryanando232@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RENGGA AGUNG SAPUTRA', 'email' => 'rengga.saputroe@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'dr. ANANINGATI, Sp. OG', 'email' => 'AKBP/71100512@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ARIF DIAN APRIANTO, S.H', 'email' => 'KOMPOL/81040450@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DODIK BINTORO, S.Psi', 'email' => 'AKP/78090637@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'dr. ARIFIAN JUARI,Sp.OG (K)', 'email' => 'IPTU/84071828@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'WIWIT AGUS HARIADI', 'email' => 'A@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'AGUS PURWANTO', 'email' => 'BRIPKA/77081143@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'GANDI ARI SETIOKO,Amd.Kep ', 'email' => 'gandiari@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DWIKI MAULANA ABDULLAH, A.md.Kep', 'email' => 'BRIPDA/97110966@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RIANTO, S.Kep Ns', 'email' => 'PENATA/196706271990031006@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FAKHRUNISAK', 'email' => 'PENATA/196706171992012001 @mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SITI SUDARYANTI, S.Sos', 'email' => 'PENDA1/196901152014122001@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'dr. YEREMIA DWI PURNOMO', 'email' => 'PENDAI/197907052005012010@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SRI WAHYUNI, Amd.Keb', 'email' => 'ysriwahyuni800@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RIZA DEWI T.', 'email' => 'rizabelva@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ANDREYAS MEMORY S', 'email' => 'PENGDA/197908302008101001@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ZAHROH, Amd.Kep', 'email' => 'PENGATUR/196904122014122001@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'UMMI IRAWATI, Amd.Keb', 'email' => 'ummi.irawati74@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'RIRIN DWI NURYANTI', 'email' => 'ririndwi613@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SESTU INGGRIATI', 'email' => 'sestuing@gmailc.om', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SURATMAN', 'email' => 'suratman.rsb26@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'NUR AFIFAH', 'email' => 'PENGATUR/197210132014122001@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'TUTI ERNAWATI', 'email' => 'watiiernaa@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'ELITA ISTYOWATI', 'email' => 'elita83cantikmanis@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SUHARMANTO', 'email' => 'manto.suhar24@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'IMAM MALIKI', 'email' => 'PENGDA/196811272014121001@mail.test', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'NUNUNG RIA', 'email' => 'nn88417053@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'BAKRI', 'email' => 'bakri.rsb30@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'DATI', 'email' => 'datibhayangkara@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'NURYATI', 'email' => 'nurbita946@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'SUKARI', 'email' => 'sukari.sukari35@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
            ['name' => 'FAKHRUL ALFIAN S.FARM', 'email' => 'fakhrulalfian.fa@gmail.com', 'password' => bcrypt('password'), 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'),],
        ]);
    }
}
